<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();
        $employees = [
            [
                'name' => 'ABDUL QODIR',
                'nip' => '01.00/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => "ACHMAD JAMA'AH",
                'nip' => '01.96/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ABDUL KOHAR',
                'nip' => '02.94/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 105000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'HABIBI',
                'nip' => '09.22/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 70000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => "ACHMAD SYAFI'I",
                'nip' => '03.93/SS/BP',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 3,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'BAMBANG JAMAL',
                'nip' => '04.89/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'M.ARIEF ABDUL LATIF',
                'nip' => '05.08/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'HENDRIK NUGROHO',
                'nip' => '03.17/SS/BP',
                'salary_per_month' => null,
                'salary_per_day' => 85000,
                'position_id' => 3,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'DJUKI',
                'nip' => '06.93/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'KUSNO',
                'nip' => '08.87/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'GITAR SAPUTRA',
                'nip' => '08.87/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 105000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'NY ANIS',
                'nip' => '10.23/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 65000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SDR ANDIKA KURNIAWAN',
                'nip' => '10.23/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 65000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MARDJONO',
                'nip' => '09.94/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JAMAAH B',
                'nip' => '09.99/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOKO MULYONO',
                'nip' => '10.92/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'FIHRIS',
                'nip' => '05.24/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 65000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SUPARMAN',
                'nip' => '11.93/SS/BP',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 3,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MUCH AMRUL',
                'nip' => '14.01/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 75000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'NY SRIRAHAYU',
                'nip' => '15.03/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 75000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RACHMAN',
                'nip' => '16.04/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'NY MUTHOHAROH',
                'nip' => '16.97/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'MOCH SHOLEH',
                'nip' => '18.07/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 75000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RONDJI',
                'nip' => '18.80/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 105000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SLAMET SUHARDI',
                'nip' => '19.03/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SUTRIMO',
                'nip' => '06.20/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SAFIRA AFIANTI',
                'nip' => '06.20/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 75000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SUPARDI',
                'nip' => '20.00/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 105000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'S.RIYANTO B',
                'nip' => '09.16/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 85000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'M.ABDUL MUIZZ',
                'nip' => '09.16/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 85000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SUTARDI',
                'nip' => '24.94/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ABDUL ROHMAN',
                'nip' => '04.14/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 75000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ACHMAD AZIZ',
                'nip' => '05.14/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 90000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'TRIYANTO',
                'nip' => '27.94/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'HENY HANDAYANI',
                'nip' => '06.14/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 65000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'RETNO JUMIATI',
                'nip' => '07.14/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 70000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'KUSDI',
                'nip' => '08.14/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 57500,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SAMIAN',
                'nip' => '28.10/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 60000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SUKIRMAN',
                'nip' => '28.86/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'M.ABDUL LATIEF',
                'nip' => '29.07/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 80000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ZAENAL MUTTAQIM',
                'nip' => '29.90/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 85000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SULIKAN',
                'nip' => '29.90/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ABDUL QODIR B',
                'nip' => '30.07/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 100000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SLAMET KARBIT',
                'nip' => '30.10/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'SULISTYONO',
                'nip' => '30.86/SS/BP',
                'salary_per_month' => null,
                'salary_per_day' => 105000,
                'position_id' => 3,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'NOOR ROHMAD',
                'nip' => '31.08/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ABD MUNIF',
                'nip' => '12.22/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 70000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'YUDI',
                'nip' => '31.93/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 95000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'HARJO SASMITO',
                'nip' => '32.08/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 87500,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'JOHAN PUNGKI',
                'nip' => '12.18/SS/OT',
                'salary_per_month' => null,
                'salary_per_day' => 85000,
                'position_id' => 2,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'M.NOOR HAFID',
                'nip' => '12.24/SS/KO',
                'salary_per_month' => null,
                'salary_per_day' => 65000,
                'position_id' => 1,
                'salary_type' => 'daily',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'BP. H. IMAM SANTIKO',
                'nip' => '02.STAFF/SS/2',
                'salary_per_month' => 6500000,
                'salary_per_day' => 216500,
                'position_id' => 4,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'ALI H.BIN H.HARNO',
                'nip' => '03.STAFF/SS/3',
                'salary_per_month' => 3500000,
                'salary_per_day' => 116500,
                'position_id' => 4,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'IBU HJ PUJI HARTINI',
                'nip' => '04.STAFF/SS/4',
                'salary_per_month' => 3300000,
                'salary_per_day' => 110000,
                'position_id' => 4,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'BP DRS H JANUAR HERRY',
                'nip' => '05.89/SS/ST',
                'salary_per_month' => 5300000,
                'salary_per_day' => 176500,
                'position_id' => 4,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'BP H. BAMBANG AK',
                'nip' => '06.89/SS/ST',
                'salary_per_month' => 2800000,
                'salary_per_day' => 93000,
                'position_id' => 4,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'BP KANDAR',
                'nip' => '07.81/SS/KO',
                'salary_per_month' => 4150000,
                'salary_per_day' => 138000,
                'position_id' => 5,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'FAFA',
                'nip' => 'DONATUR-1',
                'salary_per_month' => 1500000,
                'salary_per_day' => 50000,
                'position_id' => 5,
                'salary_type' => 'monthly',
                'join_date' => $now->format('Y-m-d'),
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        Employee::insert($employees);
    }
}
